# Fase de análisis de datos

En esta parte de estudiarán conjuntos de datos para entender la parte analítica predictiva. por lo que exploraremos:

- **Conjunto de datos estándar**
- **Estadística Descriptiva**
- **Visualización**

<Nota>: el 80% del éxcito de nuestro analisis de datos es del 
- Data Wrangling esto es con pandas
- Data Munging esto es con pandas
- Data Pre-processing
- Data Tudying
- Data cleaning
- Data Cleansging

**El ingeniero de datos es el que extrae y almacena información para que el cientifico de datos la pueda trabajar.**


## Distintos perfiles profesionales

**Data scientist** -> Más desarrollador y analista

**Data Engineer** -> Trabja con las DD, ficheros en bruto.. es decir trabaja 

## Origen de los datos

Hay modelos de datos diferentes por cada aplicación.

## Fromato de los datos

### El problema conque vamos a trabajar

El data frame es un problema real, los datos originales no vendrán en un formato propicio para su análisis directo (estructurado)

Vamos a trabjar el **Machine Learning** en la cual siepre tendremos nuestros atributos y la clase la cual será Species y tenemos que la flor va a ser de tipo setosa.
Entrenaremos al algormitmo con los datos de setosas y entonces nosotros le pasaremos datos NO ETIQUETADOS y tiene que predecirnos de acuerdo a sus características va a tratar de predecir a qué especie corresponde esos datos.

## Tipos de datos
- **Datos estructurados**: Los que están en bases de datos. Se trabaja el ing de datos
- **Dasos semi-estructurados** Datos semiestructurados en la cual no tenemos un modelo de datos, son de tipo JSON, XML. Aquí el ing de datos pero ya podemos trabajarlo
- **Datos no etructurados**: Multimedia, texto libre, requiere ser transformada para su análisis. Extracción de características.

clasificacióm lógistica es donde tenemos la clase categórica una variable cualitativa 
Regresión es donde tenemos una clase numérica

## Entender nuestros datos
 - Error Típico: Tabajar directamente algoritmos sin conocer nuestros datos.
 - Una buena cocina de datos (<análisis y procesamiento>) nos lleva a obtener mejores y más confiables resultados, entendiendo nuestros conjunto de datos.

 - Las tareas a realizar son:
     - **Limpieza de datos**: Descubrir datos corrputos o faltantes.
     - **Transformación de datos**: Descubrir una distribución com la gaussiana o exponnencial que nos genera una idea de qué técnica utilizar y si no pues aplicar una transformación para que los datos se asemejen a esas distribuciones.
     - **Modelado de datos**: A través de la esetadística descriptiva obtenemos una idea de qué algoritmo poder utilizar. Si conozco cómo están esos datos puedo suponer qué algoritmo le vendría bien a los datos. Si solo tenemos datos numéricos y son semejantes podríamos utilizar regresión lineal. Datos con mucha varianza aplicamos una estándarización. 
       - <El machine Learning es una ciencia empírica, va a base de prueba y error todo depende de la naturaleza de los datos>
     - <Nota> Nos interesa alta correlación entre las características y la clase y baja entre caracteríticas
## Asimetría
Con esto podemos ver le cesgo eso se hace con la representación de los datos.
<Usamos gráficos y diagramas para ver los cesgos>




# Diferentes formas de cargar datos en python

## Dede la librería estándar

La API de Python proporciona el módulo CSV y funciones <reader()> que se pueden usar para cargar archivos CSV. Una vez cargado, puede convertir los datos CSV a un array **NumPy** y usarlos para el *Machine Learning*. Por ejemplo, puede descargar el conjunto de datos de los indis Pima en su directorio locarl con el nombre de archivo <pima-inddians-diabetes.data.csv>. Todos los campos en este conjunto de datos son numéricos y no hay na línea de encabezado. el ejemplo de carga un objeto que puede iterar sobre cada fila de datos y puede convertirse fácilmente en un arra NumPy. Ejecutar el ejemplo imprime la forma del array

In [5]:
# Cargando CSV usando la librería estándar

import csv
import numpy as np

filename = 'data/pima-indians-diabetes.csv'
raw_data = open(filename, 'r')
reader = csv.reader(raw_data, delimiter=',', quoting= csv. QUOTE_NONE)
x = list(reader)
data = np.array(x).astype('float')
print(data)
print(data.shape)

[[  6. 148.  72. ... 627.  50.   1.]
 [  1.  85.  66. ... 351.  31.   0.]
 [  8. 183.  64. ... 672.  32.   1.]
 ...
 [  5. 121.  72. ... 245.  30.   0.]
 [  1. 126.  60. ... 349.  47.   1.]
 [  1.  93.  70. ... 315.  23.   0.]]
(768, 9)


## Desde Numpy 

Puede crgar sus datos CSV usando Numpy y la función < numpy.loadtxt() >. Esta función no supone una fila de encabezado y todos los datos tienen el mismo formato. El situiente ejemplo supone que el archivo <pima-indians-diabetes.data.csv> está en su directorio de trabajo actual. Ejecutar el ejemplo cargará el archivo como <numpy.ndarray> e imprimirá la forma de los datos 

In [6]:
# carcando csv usando NumPy

import numpy as np

filename = 'data/pima-indians-diabetes.csv'
raw_data = open(filename, 'rb')# CUANDO TRABAJAMOS CON ARCHIVOS NUMPY SE TIENE QUE PONER RB INDICANDO QUE ES DE MANERA BINARIA 
data = np.loadtxt(raw_data,delimiter=',')
print(data)

[[  6. 148.  72. ... 627.  50.   1.]
 [  1.  85.  66. ... 351.  31.   0.]
 [  8. 183.  64. ... 672.  32.   1.]
 ...
 [  5. 121.  72. ... 245.  30.   0.]
 [  1. 126.  60. ... 349.  47.   1.]
 [  1.  93.  70. ... 315.  23.   0.]]


## Con pandas

Puede cargas sus datos CSV usando Pandas y la función <pandas.read_csv()>. Esta función es muy flecible y es quizás mi enfoque recomendado para cargar sus datos de *Machine Learning*. La función devuelve un pandas. DataFrame que puede comenzar a resumir y trazar de inmediato. El siguiente ejemplo supone que el archivo <pima-idians-diabetes.csv> está en el directorio de trabajo actual. Tenga en cuenta que en este ejemplo especifiacmos explícitamente los nombres de cada atributo al DataFrame.

In [8]:
# cargando datos usando pandas

import pandas as pd
filename = 'data/pima-indians-diabetes.csv'
nombres = ['preg','plas','pres','skin','test','mass','pedi','age','class']
data = pd.read_csv(filename, names=nombres)
print(data.shape)
data

(768, 9)


preg  plas  pres  skin  test  mass     pedi  age  class
0       6   148    72    35     0  33.6   627.00   50      1
1       1    85    66    29     0  26.6   351.00   31      0
2       8   183    64     0     0  23.3   672.00   32      1
3       1    89    66    23    94  28.1   167.00   21      0
4       0   137    40    35   168  43.1  2288.00   33      1
..    ...   ...   ...   ...   ...   ...      ...  ...    ...
763    10   101    76    48   180  32.9   171.00   63      0
764     2   122    70    27     0  36.8     0.34   27      0
765     5   121    72    23   112  26.2   245.00   30      0
766     1   126    60     0     0  30.1   349.00   47      1
767     1    93    70    31     0  30.4   315.00   23      0

[768 rows x 9 columns]

In [ ]:
# cargando desde una url
import pandas as pd


url = ''# aquí carga la url donde este tu csv
dataframe = pd.read_csv(url, header=None)
dataframe